/**
 * @generated
 * @file FormWrapper (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import { Button } from "./Button";
import { Input } from "./Input";

/**
 * FormWrapper
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
export function FormWrapper({ formBody = "" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"div-block-2"} tag={"div"}>
        {formBody ?? (
          <>
            <Input />
            <Button />
          </>
        )}
      </Block>
    </div>
  );
}
