/**
 * @generated
 * @file SevenDayForecast (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import { ForecastCard } from "./ForecastCard";

/**
 * SevenDayForecast
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
export function SevenDayForecast({
  forecastCardDayOfWeek = "Monday",
  forecastCardHigh = "H: 72°",
  forecastCardHigh2 = "H: 72°",
  forecastCardHigh3 = "H: 72°",
  forecastCardHigh4 = "H: 72°",
  forecastCardHigh5 = (
    <>
      {"H: "}
      {"°"}
    </>
  ),
  forecastCardIconImage = "https://cdn.prod.website-files.com/69f4eaf4900fadf24eff1d03/69f4eaf7900fadf24eff1e10_Group%201287.png",
  forecastCardLow = "L: 55°",
  forecastCardLow2 = "L: 55°",
  forecastCardLow3 = "L: 55°",
  forecastCardLow4 = "L: 55°",
  forecastCardLow5 = (
    <>
      {"L: "}
      {"°"}
    </>
  ),
  forecastCardTemp = "63º",
  forecastCardTuesdayDayOfWeek = "Tuesday",
  forecastCardWeatherDesc = "Partly cloudy",
  forecastCardWeatherDesc2 = "Rain",
  forecastCardWeatherDesc3 = "Partially cloudy",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"block"} tag={"div"}>
        <Block className={"title"} tag={"div"}>
          {"7-Day Forecast"}
        </Block>
        <Block className={"grid-06"} tag={"div"}>
          <ForecastCard
            dayOfWeek={forecastCardDayOfWeek}
            high={forecastCardHigh5}
            iconImage={forecastCardIconImage}
            low={forecastCardLow5}
            temp={forecastCardTemp}
            weatherDesc={forecastCardWeatherDesc3}
          />
          <ForecastCard
            dayOfWeek={forecastCardTuesdayDayOfWeek}
            high={forecastCardHigh5}
            iconImage={forecastCardIconImage}
            low={forecastCardLow5}
            temp={forecastCardTemp}
            weatherDesc={forecastCardWeatherDesc3}
          />
          <ForecastCard
            dayOfWeek={forecastCardDayOfWeek}
            high={forecastCardHigh5}
            iconImage={forecastCardIconImage}
            low={forecastCardLow5}
            temp={forecastCardTemp}
            weatherDesc={forecastCardWeatherDesc3}
          />
          <ForecastCard
            dayOfWeek={forecastCardDayOfWeek}
            high={forecastCardHigh5}
            iconImage={forecastCardIconImage}
            low={forecastCardLow5}
            temp={forecastCardTemp}
            weatherDesc={forecastCardWeatherDesc3}
          />
          <ForecastCard
            dayOfWeek={forecastCardDayOfWeek}
            high={forecastCardHigh5}
            iconImage={forecastCardIconImage}
            low={forecastCardLow5}
            temp={forecastCardTemp}
            weatherDesc={forecastCardWeatherDesc3}
          />
          <ForecastCard
            dayOfWeek={forecastCardDayOfWeek}
            high={forecastCardHigh5}
            iconImage={forecastCardIconImage}
            low={forecastCardLow5}
            temp={forecastCardTemp}
            weatherDesc={forecastCardWeatherDesc3}
          />
          <ForecastCard
            dayOfWeek={forecastCardDayOfWeek}
            high={forecastCardHigh5}
            iconImage={forecastCardIconImage}
            low={forecastCardLow5}
            temp={forecastCardTemp}
            weatherDesc={forecastCardWeatherDesc3}
          />
        </Block>
      </Block>
    </div>
  );
}
