/**
 * @generated
 * @file Button (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import FormButton from "./webflow_modules/Form/components/FormButton";

/**
 * Props for {@link Button}
 */
export type ButtonProps = {};

/**
 * Button
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
export function Button({}: ButtonProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <FormButton
        className={"submit-button"}
        data-wait={"Please wait..."}
        type={"submit"}
        value={"Add location"}
      />
    </div>
  );
}
