/**
 * @generated
 * @file CurrentForecast (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link CurrentForecast}
 */
export type CurrentForecastProps = {
  aqi?: React.ReactNode;
  currentTemp?: React.ReactNode;
  feelsLikeTemp?: React.ReactNode;
  humidity?: React.ReactNode;
  precipitation?: React.ReactNode;
  sunset?: React.ReactNode;
};

/**
 * CurrentForecast
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
export function CurrentForecast({
  aqi = "70",
  currentTemp = "63º",
  feelsLikeTemp = "67º",
  humidity = "51%",
  precipitation = '.75"',
  sunset = "6:50pm",
}: CurrentForecastProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"block"} tag={"div"}>
        <Block className={"title"} tag={"div"}>
          {"Current"}
        </Block>
        <Block className={"grid-03"} tag={"div"}>
          <Block className={"card"} tag={"div"}>
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7eda_Temp.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Temperature"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {currentTemp}
              </Block>
            </Block>
          </Block>
          <Block className={"card"} tag={"div"}>
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7eda_Temp.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Feels like"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {feelsLikeTemp}
              </Block>
            </Block>
          </Block>
          <Block className={"card"} tag={"div"}>
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7eec_humidity.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Humidity"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {humidity}
              </Block>
            </Block>
          </Block>
          <Block className={"card"} tag={"div"}>
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7ec3_Precipitation.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Precipitation"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {precipitation}
              </Block>
            </Block>
          </Block>
          <Block className={"card"} tag={"div"}>
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7ec8_AQI.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Outdoor AQI"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {aqi}
              </Block>
            </Block>
          </Block>
          <Block className={"card"} tag={"div"}>
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7ed9_sunset.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Sunset"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {sunset}
              </Block>
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
