/**
 * @generated
 * @file CurrentForecast (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link CurrentForecast}
 */
export type CurrentForecastProps = {
  aqi?: React.ReactNode;
  currentTemp?: React.ReactNode;
  feelsLikeTemp?: React.ReactNode;
  humidity?: React.ReactNode;
  precipitation?: React.ReactNode;
  sunset?: React.ReactNode;
};

/**
 * CurrentForecast
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
export function CurrentForecast({
  aqi = "70",
  currentTemp = "63º",
  feelsLikeTemp = "67º",
  humidity = "51%",
  precipitation = '.75"',
  sunset = "6:50pm",
}: CurrentForecastProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"block"} tag={"div"}>
        <Block className={"title"} tag={"div"}>
          {"Current"}
        </Block>
        <Block className={"grid-03"} tag={"div"}>
          <Block
            className={"card"}
            id={"w-node-_6b29cadb-85e1-c6aa-61dc-296170e735cd-70e735c9"}
            tag={"div"}
          >
            <Block className={"flex"} tag={"div"}>
              <Block
                className={"current-content"}
                id={"w-node-_6b29cadb-85e1-c6aa-61dc-296170e735cf-70e735c9"}
                tag={"div"}
              >
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/69f4eaf4900fadf24eff1d03/69f4eaf7900fadf24eff1dfd_Temp.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Temperature"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {currentTemp}
              </Block>
            </Block>
          </Block>
          <Block
            className={"card"}
            id={"w-node-_6b29cadb-85e1-c6aa-61dc-296170e735d5-70e735c9"}
            tag={"div"}
          >
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/69f4eaf4900fadf24eff1d03/69f4eaf7900fadf24eff1dfd_Temp.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Feels like"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {feelsLikeTemp}
              </Block>
            </Block>
          </Block>
          <Block
            className={"card"}
            id={"w-node-_6b29cadb-85e1-c6aa-61dc-296170e735dd-70e735c9"}
            tag={"div"}
          >
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/69f4eaf4900fadf24eff1d03/69f4eaf7900fadf24eff1e0f_humidity.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Humidity"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {humidity}
              </Block>
            </Block>
          </Block>
          <Block
            className={"card"}
            id={"w-node-_6b29cadb-85e1-c6aa-61dc-296170e735e5-70e735c9"}
            tag={"div"}
          >
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/69f4eaf4900fadf24eff1d03/69f4eaf7900fadf24eff1de6_Precipitation.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Precipitation"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {precipitation}
              </Block>
            </Block>
          </Block>
          <Block
            className={"card"}
            id={"w-node-_6b29cadb-85e1-c6aa-61dc-296170e735ed-70e735c9"}
            tag={"div"}
          >
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/69f4eaf4900fadf24eff1d03/69f4eaf7900fadf24eff1deb_AQI.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Outdoor AQI"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {aqi}
              </Block>
            </Block>
          </Block>
          <Block
            className={"card"}
            id={"w-node-_6b29cadb-85e1-c6aa-61dc-296170e735f5-70e735c9"}
            tag={"div"}
          >
            <Block className={"flex"} tag={"div"}>
              <Block className={"current-content"} tag={"div"}>
                <Image
                  alt={""}
                  className={"icon"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/69f4eaf4900fadf24eff1d03/69f4eaf7900fadf24eff1dfc_sunset.svg"
                  }
                  width={"auto"}
                />
                <Block className={"label"} tag={"div"}>
                  {"Sunset"}
                </Block>
              </Block>
              <Block className={"label-highlight"} tag={"div"}>
                {sunset}
              </Block>
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
