/**
 * @generated
 * @file FormWrapper (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import { Button } from "./Button";
import { Input } from "./Input";

/**
 * Props for {@link FormWrapper}
 */
export type FormWrapperProps = {
  formBody?: React.ReactNode;
};

/**
 * FormWrapper
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
export function FormWrapper({ formBody = "" }: FormWrapperProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"div-block-2"} tag={"div"}>
        {formBody ?? (
          <>
            <Input />
            <Button />
          </>
        )}
      </Block>
    </div>
  );
}
