/**
 * @generated
 * @file Input (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import FormTextInput from "./webflow_modules/Form/components/FormTextInput";

/**
 * Props for {@link Input}
 */
export type InputProps = {};

/**
 * Input
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
export function Input({}: InputProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <FormTextInput
        autoFocus={false}
        className={"text-field"}
        data-name={"Location 5"}
        disabled={false}
        id={"Location-5"}
        maxLength={256}
        name={"Location-5"}
        placeholder={"Seattle, WA"}
        required={true}
        type={"text"}
      />
    </div>
  );
}
