/**
 * @generated
 * @file LocationForm (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import FormErrorMessage from "./webflow_modules/Form/components/FormErrorMessage";
import FormForm from "./webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "./webflow_modules/Form/components/FormSuccessMessage";
import FormWrapper2 from "./webflow_modules/Form/components/FormWrapper";
import { FormWrapper } from "./FormWrapper";

/**
 * Props for {@link LocationForm}
 */
export type LocationFormProps = {
  errorMessage?: React.ReactNode;
  formBody?: React.ReactNode;
  successMessage?: React.ReactNode;
};

/**
 * LocationForm
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
export function LocationForm({
  errorMessage = "Oops! Can't add this location.",
  formBody = "",
  successMessage = "Successfully added new location!",
}: LocationFormProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <FormWrapper2 className={"form-block"}>
        <FormForm
          className={"form"}
          data-name={"Location Form"}
          id={"wf-form-Location-Form"}
          method={"get"}
          name={"wf-form-Location-Form"}
        >
          <FormWrapper formBody={formBody} />
        </FormForm>
        <FormSuccessMessage className={"success-message"}>
          <Block className={""} tag={"div"}>
            {successMessage}
          </Block>
        </FormSuccessMessage>
        <FormErrorMessage className={"error-message"}>
          <Block className={"text-block"} tag={"div"}>
            {errorMessage}
          </Block>
        </FormErrorMessage>
      </FormWrapper2>
    </div>
  );
}
