/**
 * @generated
 * @file SavedLocations (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link SavedLocations}
 */
export type SavedLocationsProps = {};

/**
 * SavedLocations
 *
 * @see {@link https://weather-app-0ffc12.design.webflow.com | Source site in Webflow}
 */
export function SavedLocations({}: SavedLocationsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"block"} tag={"div"}>
        <Block className={"title"} tag={"div"}>
          {"Saved Locations"}
        </Block>
        <Block className={"list"} tag={"div"}>
          <Link
            block={"inline"}
            button={false}
            className={"card"}
            options={{
              href: "#",
            }}
          >
            <Block className={"flex"} tag={"div"}>
              <Block tag={"div"}>
                <Block className={"label-highlight"} tag={"div"}>
                  {"Atlanta - Mostly Cloudy"}
                </Block>
                <Block className={"label"} tag={"div"}>
                  {"2:17pm"}
                </Block>
              </Block>
              <Block className={"flex"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-small"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7eed_Group%201287.png"
                  }
                  width={"auto"}
                />
                <Block className={"temp-small"} tag={"div"}>
                  {"74º"}
                </Block>
              </Block>
            </Block>
          </Link>
          <Link
            block={"inline"}
            button={false}
            className={"card"}
            options={{
              href: "#",
            }}
          >
            <Block className={"flex"} tag={"div"}>
              <Block tag={"div"}>
                <Block className={"label-highlight"} tag={"div"}>
                  {"New York - Drizzle"}
                </Block>
                <Block className={"label"} tag={"div"}>
                  {"2:17pm"}
                </Block>
              </Block>
              <Block className={"flex"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-small"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7ef4_Group%201263.png"
                  }
                  width={"auto"}
                />
                <Block className={"temp-small"} tag={"div"}>
                  {"65º"}
                </Block>
              </Block>
            </Block>
          </Link>
          <Link
            block={"inline"}
            button={false}
            className={"card"}
            options={{
              href: "#",
            }}
          >
            <Block className={"flex"} tag={"div"}>
              <Block tag={"div"}>
                <Block className={"label-highlight"} tag={"div"}>
                  {"Amsterdam - Severe storms"}
                </Block>
                <Block className={"label"} tag={"div"}>
                  {"8:17pm"}
                </Block>
              </Block>
              <Block className={"flex"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-small"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6a01f7d620f963e808ee7dc3/6a01f7d920f963e808ee7ef3_Group%201273.png"
                  }
                  width={"auto"}
                />
                <Block className={"temp-small"} tag={"div"}>
                  {"80º"}
                </Block>
              </Block>
            </Block>
          </Link>
        </Block>
      </Block>
    </div>
  );
}
