/**
 * @generated
 * @file SevenDayForecast (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import { ForecastCard } from "./ForecastCard";

/**
 * Props for {@link SevenDayForecast}
 */
export type SevenDayForecastProps = {
  forecastCardHigh?: React.ReactNode;
  forecastCardHigh2?: React.ReactNode;
  forecastCardHigh3?: React.ReactNode;
  forecastCardHigh4?: React.ReactNode;
  forecastCardLow?: React.ReactNode;
  forecastCardLow2?: React.ReactNode;
  forecastCardLow3?: React.ReactNode;
  forecastCardLow4?: React.ReactNode;
  forecastCardWeatherDesc?: React.ReactNode;
  forecastCardWeatherDesc2?: React.ReactNode;
};

/**
 * SevenDayForecast
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
export function SevenDayForecast({
  forecastCardHigh = "H: 72°",
  forecastCardHigh2 = "H: 72°",
  forecastCardHigh3 = "H: 72°",
  forecastCardHigh4 = "H: 72°",
  forecastCardLow = "L: 55°",
  forecastCardLow2 = "L: 55°",
  forecastCardLow3 = "L: 55°",
  forecastCardLow4 = "L: 55°",
  forecastCardWeatherDesc = "Partly cloudy",
  forecastCardWeatherDesc2 = "Rain",
}: SevenDayForecastProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"block"} tag={"div"}>
        <Block className={"title"} tag={"div"}>
          {"7-Day Forecast"}
        </Block>
        <Block className={"grid-06"} tag={"div"}>
          <ForecastCard />
        </Block>
      </Block>
    </div>
  );
}
