/**
 * @generated
 * @file TopNav (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import DropdownList from "./webflow_modules/Dropdown/components/DropdownList";
import DropdownToggle from "./webflow_modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "./webflow_modules/Dropdown/components/DropdownWrapper";
import Icon from "./webflow_modules/Icon/components/Icon";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link TopNav}
 */
export type TopNavProps = {};

/**
 * TopNav
 *
 * @see {@link https://devlink-weather-2cccd8.design.webflow.com | Source site in Webflow}
 */
export function TopNav({}: TopNavProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"top-nav"} tag={"div"}>
        <Block className={"dashboard-nav-container"} tag={"div"}>
          <DropdownWrapper
            className={"dropdown"}
            delay={0}
            hover={false}
            tag={"div"}
          >
            <DropdownToggle className={"dropdown-toggle"} tag={"div"}>
              <Icon
                className={"arrow-down"}
                widget={{
                  type: "icon",
                  icon: "dropdown-toggle",
                }}
              />
              <Block className={"title-large"} tag={"div"}>
                {"San Francisco"}
              </Block>
            </DropdownToggle>
            <DropdownList className={"dropdown-list"} tag={"nav"}>
              <Link
                block={"inline"}
                button={false}
                className={"flex"}
                options={{
                  href: "#",
                }}
              >
                <Block tag={"div"}>
                  <Block className={"label-highlight"} tag={"div"}>
                    {"Atlanta - Mostly Cloudy"}
                  </Block>
                  <Block className={"label"} tag={"div"}>
                    {"2:17pm"}
                  </Block>
                </Block>
                <Block className={"temp-small"} tag={"div"}>
                  {"74º"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"dropdown-card"}
                options={{
                  href: "#",
                }}
              >
                <Block tag={"div"}>
                  <Block className={"label-highlight"} tag={"div"}>
                    {"New York - Drizzle"}
                  </Block>
                  <Block className={"label"} tag={"div"}>
                    {"2:17pm"}
                  </Block>
                </Block>
                <Block className={"temp-small"} tag={"div"}>
                  {"65º"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"flex"}
                options={{
                  href: "#",
                }}
              >
                <Block tag={"div"}>
                  <Block className={"label-highlight"} tag={"div"}>
                    {"Spain - Sun"}
                  </Block>
                  <Block className={"label"} tag={"div"}>
                    {"2:17pm"}
                  </Block>
                </Block>
                <Block className={"temp-small"} tag={"div"}>
                  {"80º"}
                </Block>
              </Link>
            </DropdownList>
          </DropdownWrapper>
        </Block>
      </Block>
    </div>
  );
}
